routes/web.php
<?php

use App\Http\Controllers\Sahil\api\SocialAuthController;
use App\Http\Controllers\dashboard\admin\AdminLoginController;
use App\Http\Controllers\dashboard\admin\AgentsController;
use App\Http\Controllers\dashboard\admin\BrandController;
use App\Http\Controllers\dashboard\admin\CategoryController;
use App\Http\Controllers\dashboard\admin\CouponController;
use App\Http\Controllers\dashboard\admin\EmployeesController;
use App\Http\Controllers\dashboard\admin\OrderController;
use App\Http\Controllers\dashboard\admin\ProductController;
use App\Http\Controllers\dashboard\admin\SubCategoryController;
use App\Http\Controllers\dashboard\admin\UserController;
use App\Http\Controllers\dashboard\admin\VendorController;
use App\Http\Controllers\dashboard\admin\GroupController;
use App\Http\Controllers\dashboard\admin\PasswordController;
use App\Http\Controllers\dashboard\admin\SettingController;
use App\Http\Controllers\dashboard\vendor\VendorSalesController;
use Illuminate\Support\Facades\Route;

Route::get('forgot-password', [PasswordController::class, 'forgotPassword'])->name('forgot.password');
Route::post('/send-otp-by-email',[PasswordController::class, 'sendOtp'])->name('sendOtp');
Route::get('/enter-otp', [PasswordController::class,'enterOtp'])->name('enter.otp');
Route::get('/enter-password', [PasswordController::class,'enterPassword'])->name('enter.password');
Route::post('/reset-password', [PasswordController::class,'resetPassword'])->name('reset.password');
Route::post('/verify-otp',[PasswordController::class, 'verifyOtp'])->name('verify.otp');

Route::prefix('dashboard')->group(function (){
        Route::get('/login',[AdminLoginController::class,'index'])->name('login');
        Route::post('/authenticate',[AdminLoginController::class,'authenticate'])->name('authenticate');
});

Route::prefix('dashboard')->group(function () {
    Route::middleware('auth:sanctum')->group(function () {
        Route::get('/',[AdminLoginController::class,'dashboard'])->name('dashboard');
        Route::get('/logout',[AdminLoginController::class,'logout'])->name('logout');

        Route::get('/change-password',[PasswordController::class,'changePassword'])->name('change.password');
        Route::post('/update-password',[PasswordController::class,'updatePassword'])->name('update.password');

        Route::resource('categories', CategoryController::class)->except(['show']);
        Route::resource('subcategories',SubCategoryController::class)->except(['show']);
        Route::resource('brands',BrandController::class)->except(['show']);
        Route::resource('coupons',CouponController::class)->except(['show']);

        Route::resource('vendors',VendorController::class)->only(['index','destroy']);
        Route::get('/vendor/sales', [VendorSalesController::class, 'index'])->name('vendor.sales.index');

        Route::resource('orders',OrderController::class)->only(['index','destroy']);
        Route::resource('users',UserController::class)->only(['index']);
        Route::resource('employees',EmployeesController::class)->except(['show']);
        Route::resource('agents',AgentsController::class)->except(['show']);
        Route::resource('groups',GroupController::class)->only(['index']);

        Route::resource('products',ProductController::class)->except(['show','edit','update']);
        Route::get('/products/{product}/details/{productDetail}/edit', [ProductController::class, 'edit'])->name('products.edit');
        Route::put('/products/{productId}/details/{productDetailId}', [ProductController::class, 'update'])->name('products.update');
        
        Route::get('/settings', [SettingController::class, 'index'])->name('settings.index');
        Route::post('/settings/update', [SettingController::class, 'createOrupdate'])->name('settings.update');
    });
    
});

Route::get('/product-subcategories',[ProductController::class,'SubCategoriesToCreateProduct'])->name('product_subcategories.index');
Route::get('/product-sizes',[ProductController::class,'SizesToCreateProduct'])->name('product_sizes.index');



// Social Login Routes
Route::get('auth/google',[SocialAuthController::class, 'redirectToGoogle']); 
Route::get('auth/google/callback',[SocialAuthController::class, 'googleCallback']);

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sahil :: Dashboard</title>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('admin-assets/plugins/fontawesome-free/css/all.min.css')}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('admin-assets/css/adminlte.min.css')}}">
    <link rel="stylesheet" href="{{asset('admin-assets/css/custom.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Right navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
        </ul>
        <div class="navbar-nav pl-2">

        </div>

        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                    <i class="fas fa-expand-arrows-alt"></i>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link p-0 pr-3" data-toggle="dropdown" href="#">
                    <img src="{{ asset(Auth::user()->profile_image 
                    ? 'imgs/' . Auth::user()->profile_image 
                    : 'admin-assets/img/avatar4.png') }}" class="img-circle elevation-2" width="40" height="40" alt="">
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right p-3">
                    <h4 class="h4 mb-0"><strong>{{Auth::user()->name}}</strong></h4>
                    <div class="mb-3">{{Auth::user()->email}}</div>
                    <div class="dropdown-divider"></div>
                    <a href="{{route('settings.index')}}" class="dropdown-item">
                        <i class="fas fa-user-cog mr-2"></i> Settings
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{{route('change.password')}}" class="dropdown-item">
                        <i class="fas fa-lock mr-2"></i> Change Password
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{{route('logout')}}" class="dropdown-item text-danger">
                        <i class="fas fa-sign-out-alt mr-2"></i> Logout
                    </a>
                </div>
            </li>
        </ul>
    </nav>
    <!-- /.navbar -->
    <!-- Main Sidebar Container -->
    @include('admin.layouts.sidebar')
    <div class="content-wrapper">
        @yield('content')
    </div>
</div>

<!-- jQuery -->
<script src="{{asset('admin-assets/plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script src="{{asset('admin-assets/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('admin-assets/js/adminlte.min.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset('admin-assets/js/demo.js')}}"></script>
</body>
</html>

resources/views/admin/layouts/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <img src="{{asset('admin-assets/img/AdminLTELogo.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Sahil</span>
    </a>
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a href="{{route('dashboard')}}" class="nav-link">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                @if (Auth::user()->role == 'admin')
                    <li class="nav-item">
                    <a href="{{route('categories.index')}}" class="nav-link">
                        <i class="nav-icon fas fa-file-alt"></i>
                        <p>Category</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('subcategories.index')}}" class="nav-link">
                        <i class="nav-icon fas fa-file-alt"></i>
                        <p>Sub Category</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('brands.index')}}" class="nav-link">
                        <svg class="h-6 nav-icon w-6 shrink-0" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M16 4v12l-4-2-4 2V4M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                        </svg>
                        <p>Brands</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('coupons.index')}}" class="nav-link">
                        <i class="nav-icon  fa fa-percent" aria-hidden="true"></i>
                        <p>Coupons</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('users.index')}}" class="nav-link">
                        <i class="nav-icon  fas fa-users"></i>
                        <p>Users</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('employees.index')}}" class="nav-link">
                        <i class="nav-icon  fas fa-users"></i>
                        <p>Employees</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('agents.index')}}"" class="nav-link">
                        <i class="nav-icon  fas fa-users"></i>
                        <p>Agents</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('vendors.index')}}" class="nav-link">
                        <i class="nav-icon  fas fa-users"></i>
                        <p>Vendors</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('orders.index')}}" class="nav-link">
                        <i class="nav-icon fas fa-shopping-bag"></i>
                        <p>Orders</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('groups.index')}}" class="nav-link">
                        <i class="nav-icon fas fa-shopping-bag"></i>
                        <p>Groups</p>
                    </a>
                </li>
                @endif
                <li class="nav-item">
                    <a href="{{route('products.index')}}" class="nav-link">
                        <i class="nav-icon fas fa-tag"></i>
                        <p>Products</p>
                    </a>
                </li>
                @if (Auth::user()->role == 'vendor')
                <li class="nav-item">
                    <a href="{{route('vendor.sales.index')}}" class="nav-link">
                        <i class="nav-icon fas fa-shopping-bag"></i>
                        <p>Sales</p>
                    </a>
                </li>
                @endif
                {{-- <li class="nav-item">
                    <a href="users.html" class="nav-link">
                        <i class="nav-icon  fas fa-users"></i>
                        <p>Reports</p>
                    </a>
                </li> --}}
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>