routes/web.php
<?php

use App\Http\Controllers\Sahil\api\SocialAuthController;
use App\Http\Controllers\dashboard\admin\AdminLoginController;
use App\Http\Controllers\dashboard\admin\AgentsController;
use App\Http\Controllers\dashboard\admin\BrandController;
use App\Http\Controllers\dashboard\admin\CategoryController;
use App\Http\Controllers\dashboard\admin\CouponController;
use App\Http\Controllers\dashboard\admin\EmployeesController;
use App\Http\Controllers\dashboard\admin\OrderController;
use App\Http\Controllers\dashboard\admin\ProductController;
use App\Http\Controllers\dashboard\admin\SubCategoryController;
use App\Http\Controllers\dashboard\admin\UserController;
use App\Http\Controllers\dashboard\admin\VendorController;
use App\Http\Controllers\dashboard\admin\GroupController;
use App\Http\Controllers\dashboard\admin\PasswordController;
use App\Http\Controllers\dashboard\admin\SettingController;
use App\Http\Controllers\dashboard\vendor\VendorSalesController;
use Illuminate\Support\Facades\Route;

Route::get('forgot-password', [PasswordController::class, 'forgotPassword'])->name('forgot.password');
Route::post('/send-otp-by-email',[PasswordController::class, 'sendOtp'])->name('sendOtp');
Route::get('/enter-otp', [PasswordController::class,'enterOtp'])->name('enter.otp');
Route::get('/enter-password', [PasswordController::class,'enterPassword'])->name('enter.password');
Route::post('/reset-password', [PasswordController::class,'resetPassword'])->name('reset.password');
Route::post('/verify-otp',[PasswordController::class, 'verifyOtp'])->name('verify.otp');

Route::prefix('dashboard')->group(function (){
        Route::get('/login',[AdminLoginController::class,'index'])->name('login');
        Route::post('/authenticate',[AdminLoginController::class,'authenticate'])->name('authenticate');
});

Route::prefix('dashboard')->group(function () {
    Route::middleware('auth:sanctum')->group(function () {
        Route::get('/',[AdminLoginController::class,'dashboard'])->name('dashboard');
        Route::get('/logout',[AdminLoginController::class,'logout'])->name('logout');

        Route::get('/change-password',[PasswordController::class,'changePassword'])->name('change.password');
        Route::post('/update-password',[PasswordController::class,'updatePassword'])->name('update.password');

        Route::resource('categories', CategoryController::class)->except(['show']);
        Route::resource('subcategories',SubCategoryController::class)->except(['show']);
        Route::resource('brands',BrandController::class)->except(['show']);
        Route::resource('coupons',CouponController::class)->except(['show']);

        Route::resource('vendors',VendorController::class)->only(['index','destroy']);
        Route::get('/vendor/sales', [VendorSalesController::class, 'index'])->name('vendor.sales.index');

        Route::resource('orders',OrderController::class)->only(['index','destroy']);
        Route::resource('users',UserController::class)->only(['index']);
        Route::resource('employees',EmployeesController::class)->except(['show']);
        Route::resource('agents',AgentsController::class)->except(['show']);
        Route::resource('groups',GroupController::class)->only(['index']);

        Route::resource('products',ProductController::class)->except(['show','edit','update']);
        Route::get('/products/{product}/details/{productDetail}/edit', [ProductController::class, 'edit'])->name('products.edit');
        Route::put('/products/{productId}/details/{productDetailId}', [ProductController::class, 'update'])->name('products.update');
        
        Route::get('/settings', [SettingController::class, 'index'])->name('settings.index');
        Route::post('/settings/update', [SettingController::class, 'createOrupdate'])->name('settings.update');
    });
    
});

Route::get('/product-subcategories',[ProductController::class,'SubCategoriesToCreateProduct'])->name('product_subcategories.index');
Route::get('/product-sizes',[ProductController::class,'SizesToCreateProduct'])->name('product_sizes.index');



// Social Login Routes
Route::get('auth/google',[SocialAuthController::class, 'redirectToGoogle']); 
Route::get('auth/google/callback',[SocialAuthController::class, 'googleCallback']);

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Brand extends Model implements HasMedia
{
    use HasFactory, InteractsWithMedia;

    protected $keyType = 'string';
    
    protected $fillable = ['title','logo','status'];

    protected static function newFactory()
    {
        //return BrandFactory::new();
    }

    public function products() {
        return $this -> hasMany(Product::class);
    }
}

app/Http/Controllers/Sahil/api/BrandController.php
<?php

namespace App\Http\Controllers\Sahil\api;

use App\Http\Controllers\Controller;
use App\Http\Resources\Resource;
use App\Models\Brand;
use App\traits\PermissionCheckTrait;
use App\traits\ResponseTrait;
use Illuminate\Http\Request;

class BrandController extends Controller
{
    use ResponseTrait, PermissionCheckTrait;

    public function index(Request $request){
        $this->PermissionCheck($request, ['brand view']);
        $brands = Brand::paginate(1);
        $data = Resource::collection($brands)->response()->getData(true);
        return $this->dataResponse('All Brands', $data);
    }

    public function show(Request $request, string $id){
        $this->PermissionCheck($request, ['brand view']);
        $brand = Brand::find($id);
        if (!$brand) {
            return $this->errorResponse( 'No Brand For This ID: ' . $id, 404);
        }
        $data = new Resource($brand);
        return $this->dataResponse('brand', $data);
    }
}

app/Http/Controllers/dashboard/admin/BrandController.php
<?php

namespace App\Http\Controllers\dashboard\admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\BrandRequest;
use App\Models\Brand;
use App\Services\BrandService;
use App\traits\PermissionCheckTrait;
use Illuminate\Http\Request;

class BrandController extends Controller
{
    use PermissionCheckTrait;

    public function index(Request $request, BrandService $brandService){
        $this->PermissionCheck($request, ['brand view']);
        return $brandService->index($request);
    }

    public function create(){
        return view('admin.brands.create');
    }

    public function store(BrandRequest $request,BrandService $brandService){
        return $brandService -> store($request);
    }

    public function edit($brandId){
        $brand = Brand::findOrFail($brandId);
        return view('admin.brands.edit',compact('brand'));
    }

    public function update($brandId, BrandRequest $request, BrandService $brandService){
        return $brandService->update($brandId,$request);
    }
    
    public function destroy(Request $request, $brandId, BrandService $brandService){
        $this->PermissionCheck($request, ['brand delete']);
        return $brandService -> destroy($brandId);
    }
}

resources/views/admin/brands/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid my-2">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Create Brand</h1>
            </div>
            <div class="col-sm-6 text-right">
                <a href="{{route('brands.index')}}" class="btn btn-primary">Back</a>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
</section>
<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="container-fluid">
        <form action="{{route('brands.store')}}" method="post" enctype="multipart/form-data">
        @csrf
            <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label for="title">Title</label>
                            <input type="text" name="title" id="title" class="form-control @error('title')
                                    is-invalid
                                    @enderror" placeholder="Brand Title">
                            @error('title')
                            <p class="invalid-feedback">{{$message}}</p>
                            @enderror
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label for="status">Status</label>
                            <select name="status" id="status" class="form-control @error('status')
                                    is-invalid
                                    @enderror" placeholder="Category Status">
                                <option value='1'>Active</option>
                                <option value='0'>Block</option>
                            </select>
                            @error('status')
                            <p class="invalid-feedback">{{$message}}</p>
                            @enderror
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label for="formFile" class="form-label">Logo</label>
                            <input class="form-control @error('logo')
                                    is-invalid
                                    @enderror" type="file" name="logo" id="formFile">
                            @error('logo')
                            <p class="invalid-feedback">{{$message}}</p>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="pb-5 pt-3">
            <button class="btn btn-primary">Create</button>
            <a href="{{route('brands.index')}}" class="btn btn-outline-dark ml-3">Cancel</a>
        </div>
        </form>
    </div>
    <!-- /.card -->
</section>
<!-- /.content -->
@endsection

resources/views/admin/brands/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid my-2">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Edit Brand</h1>
                </div>
                <div class="col-sm-6 text-right">
                    <a href="{{route('brands.index')}}" class="btn btn-primary">Back</a>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="container-fluid">
            <form action="{{route('brands.update',$brand->id)}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('put')
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="title">Title</label>
                                    <input type="text" name="title" id="title" class="form-control @error('title')
                                    is-invalid
                                    @enderror" value="{{$brand->title}}">
                                    @error('title')
                                    <p class="invalid-feedback">{{$message}}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="status">Status</label>
                                    <select name="status" id="status" class="form-control @error('status')
                                    is-invalid
                                    @enderror" placeholder="Category Status">
                                        <option value="1" {{$brand->status == 1 ? 'selected' : ''}}>Active</option>
                                        <option value="0" {{$brand->status == 0 ? 'selected' : ''}}>Block</option>
                                    </select>
                                    @error('status')
                                    <p class="invalid-feedback">{{$message}}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="formFile" class="form-label">Logo</label>
                                    <input class="form-control @error('logo')
                                    is-invalid
                                    @enderror" type="file" name="logo" id="formFile">
                                    @error('logo')
                                    <p class="invalid-feedback">{{$message}}</p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="pb-5 pt-3">
                    <button class="btn btn-primary">Edit</button>
                    <a href="{{route('brands.index')}}" class="btn btn-outline-dark ml-3">Cancel</a>
                </div>
            </form>
        </div>
        <!-- /.card -->
    </section>
    <!-- /.content -->
@endsection

resources/views/admin/brands/list.blade.php
@extends('admin.layouts.app')

@section('content')
<!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid my-2">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Brands</h1>
                    </div>
                    <div class="col-sm-6 text-right">
                        <a href="{{route('brands.create')}}" class="btn btn-primary">New Brand</a>
                    </div>
                </div>
            </div>
            <!-- /.container-fluid -->
            @include('admin.messages')
        </section>
        <!-- Main content -->
        <section class="content">
            <!-- Default box -->
            <div class="container-fluid">
                <div class="card">
                    <div class="card-header">
                        <div class="card-tools">
                            <div class="input-group input-group" style="width: 250px;">
                                <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-default">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover text-nowrap">
                            <thead>
                            <tr>
                                <th width="60">ID</th>
                                <th>Title</th>
                                <th width="100">Status</th>
                                <th width="100">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if($brands->isNotEmpty())
                                @foreach($brands as $brand)
                                    <tr>
                                        <td>{{$brand->id}}</td>
                                        <td>{{$brand->title}}</td>
                                        <td>
                                            @if($brand->status == 1)
                                                <svg class="text-success-500 h-6 w-6 text-success" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
                                                    <path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                                                </svg>
                                            @else
                                                <svg class="text-danger h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
                                                     <path stroke-linecap="round" stroke-linejoin="round" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                                                </svg>
                                            @endif
                                        </td>
                                        <td>
                                            <a href="{{route('brands.edit',$brand->id)}}">
                                                <svg class="filament-link-icon w-4 h-4 mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                                    <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"></path>
                                                </svg>
                                            </a>
                                            
                                        <form id="delete-form" action="{{route('brands.destroy',$brand->id)}}" method="post">
                                            @method('DELETE')
                                            @csrf
                                            <a onclick="event.preventDefault(); document.getElementById('delete-form').submit();" class="text-danger w-4 h-4 mr-1">
                                                <svg wire:loading.remove.delay="" wire:target="" class="filament-link-icon w-4 h-4 mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                                    <path	ath fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"></path>
                                                </svg>
                                            </a>
                                        </form>
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                <tr>
                                    <td colspan="5">
                                        Records Not Found
                                    </td>
                                </tr>
                            @endif
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer clearfix">
                        {{$brands->links()}}
                    </div>
                </div>
            </div>
            <!-- /.card -->
        </section>
        <!-- /.content -->
@endsection