routes/web.php
<?php

use App\Http\Controllers\Sahil\api\SocialAuthController;
use App\Http\Controllers\dashboard\admin\AdminLoginController;
use App\Http\Controllers\dashboard\admin\AgentsController;
use App\Http\Controllers\dashboard\admin\BrandController;
use App\Http\Controllers\dashboard\admin\CategoryController;
use App\Http\Controllers\dashboard\admin\CouponController;
use App\Http\Controllers\dashboard\admin\EmployeesController;
use App\Http\Controllers\dashboard\admin\OrderController;
use App\Http\Controllers\dashboard\admin\ProductController;
use App\Http\Controllers\dashboard\admin\SubCategoryController;
use App\Http\Controllers\dashboard\admin\UserController;
use App\Http\Controllers\dashboard\admin\VendorController;
use App\Http\Controllers\dashboard\admin\GroupController;
use App\Http\Controllers\dashboard\admin\PasswordController;
use App\Http\Controllers\dashboard\admin\SettingController;
use App\Http\Controllers\dashboard\vendor\VendorSalesController;
use Illuminate\Support\Facades\Route;

Route::get('forgot-password', [PasswordController::class, 'forgotPassword'])->name('forgot.password');
Route::post('/send-otp-by-email',[PasswordController::class, 'sendOtp'])->name('sendOtp');
Route::get('/enter-otp', [PasswordController::class,'enterOtp'])->name('enter.otp');
Route::get('/enter-password', [PasswordController::class,'enterPassword'])->name('enter.password');
Route::post('/reset-password', [PasswordController::class,'resetPassword'])->name('reset.password');
Route::post('/verify-otp',[PasswordController::class, 'verifyOtp'])->name('verify.otp');

Route::prefix('dashboard')->group(function (){
        Route::get('/login',[AdminLoginController::class,'index'])->name('login');
        Route::post('/authenticate',[AdminLoginController::class,'authenticate'])->name('authenticate');
});

Route::prefix('dashboard')->group(function () {
    Route::middleware('auth:sanctum')->group(function () {
        Route::get('/',[AdminLoginController::class,'dashboard'])->name('dashboard');
        Route::get('/logout',[AdminLoginController::class,'logout'])->name('logout');

        Route::get('/change-password',[PasswordController::class,'changePassword'])->name('change.password');
        Route::post('/update-password',[PasswordController::class,'updatePassword'])->name('update.password');

        Route::resource('categories', CategoryController::class)->except(['show']);
        Route::resource('subcategories',SubCategoryController::class)->except(['show']);
        Route::resource('brands',BrandController::class)->except(['show']);
        Route::resource('coupons',CouponController::class)->except(['show']);

        Route::resource('vendors',VendorController::class)->only(['index','destroy']);
        Route::get('/vendor/sales', [VendorSalesController::class, 'index'])->name('vendor.sales.index');

        Route::resource('orders',OrderController::class)->only(['index','destroy']);
        Route::resource('users',UserController::class)->only(['index']);
        Route::resource('employees',EmployeesController::class)->except(['show']);
        Route::resource('agents',AgentsController::class)->except(['show']);
        Route::resource('groups',GroupController::class)->only(['index']);

        Route::resource('products',ProductController::class)->except(['show','edit','update']);
        Route::get('/products/{product}/details/{productDetail}/edit', [ProductController::class, 'edit'])->name('products.edit');
        Route::put('/products/{productId}/details/{productDetailId}', [ProductController::class, 'update'])->name('products.update');
        
        Route::get('/settings', [SettingController::class, 'index'])->name('settings.index');
        Route::post('/settings/update', [SettingController::class, 'createOrupdate'])->name('settings.update');
    });
    
});

Route::get('/product-subcategories',[ProductController::class,'SubCategoriesToCreateProduct'])->name('product_subcategories.index');
Route::get('/product-sizes',[ProductController::class,'SizesToCreateProduct'])->name('product_sizes.index');



// Social Login Routes
Route::get('auth/google',[SocialAuthController::class, 'redirectToGoogle']); 
Route::get('auth/google/callback',[SocialAuthController::class, 'googleCallback']);

app/Models/Coupon.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Coupon extends Model
{
    use HasFactory;

    protected $fillable = ['status','code','discount','expire'];

    protected static function newFactory()
    {
        //return CouponFactory::new();
    }

    // public function orders() {
    //     return $this -> belongsTo(Order::class);
    // }
}

app/Http/Controllers/dashboard/admin/CouponController.php
<?php

namespace App\Http\Controllers\dashboard\admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CouponRequest;
use App\Services\CouponService;
use App\traits\PermissionCheckTrait;
use Illuminate\Http\Request;

class CouponController extends Controller
{
    use PermissionCheckTrait;

    public function index(Request $request, CouponService $couponService){
        $this->PermissionCheck($request, ['coupon view']);
        return $couponService -> index($request);
    }

    public function create(CouponService $couponService){
        return $couponService -> create();
    }

    public function store(CouponRequest $request, CouponService $couponService){
        return $couponService -> store($request);
    }

    public function edit($couponId, CouponService $couponService){
        return $couponService -> edit($couponId);
    }

    public function update($couponId,CouponRequest $request, CouponService $couponService){
        return $couponService -> update($couponId, $request);
    }

    public function destroy(Request $request, $couponId, CouponService $couponService){
        $this->PermissionCheck($request, ['coupon delete']);
        return $couponService -> destroy($couponId);
    }
}

resources/views/admin/coupons/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid my-2">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Create Coupon</h1>
                </div>
                <div class="col-sm-6 text-right">
                    <a href="{{route('coupons.index')}}" class="btn btn-primary">Back</a>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="container-fluid">
            <form action="{{route('coupons.store')}}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="expire">Expire Date</label>
                                    <input type="date" name="expire" id="expire" class="form-control 
                                    @error('expire')
                                    is-invalid
                                    @enderror">
                                    @error('expire')
                                    <p class="invalid-feedback">{{$message}}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="discount" class="form-label">Discount</label>
                                    <input class="form-control @error('discount')
                                    is-invalid
                                    @enderror" type="number" name="discount" id="discount">
                                    @error('discount')
                                    <p class="invalid-feedback">{{$message}}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                            <div class="mb-3">
                                <label for="status">Status</label>
                                <select name="status" id="status" class="form-control @error('status')
                                        is-invalid
                                        @enderror" placeholder="Category Status">
                                    <option value='1'>Active</option>
                                    <option value='0'>Block</option>
                                </select>
                                @error('status')
                                <p class="invalid-feedback">{{$message}}</p>
                                @enderror
                            </div>
                        </div>
                        </div>
                    </div>
                </div>

                <div class="pb-5 pt-3">
                    <button class="btn btn-primary">Create</button>
                    <a href="{{route('coupons.index')}}" class="btn btn-outline-dark ml-3">Cancel</a>
                </div>
            </form>
        </div>
        <!-- /.card -->
    </section>
    <!-- /.content -->
@endsection

resources/views/admin/coupons/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid my-2">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Edit Coupon</h1>
                </div>
                <div class="col-sm-6 text-right">
                    <a href="{{route('coupons.index')}}" class="btn btn-primary">Back</a>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="container-fluid">
            <form action="{{route('coupons.update',$coupon->id)}}" method="post" enctype="multipart/form-data">
                @method('PUT')
                @csrf
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="discount">Discount</label>
                                    <input type="text" name="discount" id="discount" class="form-control @error('discount')
                                    is-invalid
                                    @enderror" value="{{$coupon->discount}}">
                                    @error('discount')
                                    <p class="invalid-feedback">{{$message}}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="expire" class="form-label">Expire</label>
                                    <input class="form-control @error('expire')
                                    is-invalid
                                    @enderror" type="date" name="expire" id="expire" value="{{$coupon->expire}}">
                                    @error('expire')
                                    <p class="invalid-feedback">{{$message}}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="status">Status</label>
                                    <select name="status" id="status" class="form-control @error('status')
                                            is-invalid
                                            @enderror" placeholder="Category Status">
                                        <option value="1" {{$coupon->status == 1 ? 'selected' : ''}}>Active</option>
                                        <option value="0" {{$coupon->status == 0 ? 'selected' : ''}}>Block</option>
                                    </select>
                                    @error('status')
                                    <p class="invalid-feedback">{{$message}}</p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="pb-5 pt-3">
                    <button class="btn btn-primary">Edit</button>
                    <a href="{{route('coupons.index')}}" class="btn btn-outline-dark ml-3">Cancel</a>
                </div>
            </form>
        </div>
        <!-- /.card -->
    </section>
    <!-- /.content -->
@endsection

resources/views/admin/coupons/list.blade.php
@extends('admin.layouts.app')

@section('content')
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Discount Coupons</h1>
                    </div>
                    <div class="col-sm-6 text-right">
                        <a href="{{route('coupons.create')}}" class="btn btn-primary">New Coupon</a>
                    </div>
                </div>
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <!-- Default box -->
            <div class="container-fluid">
                <div class="card">
                    <form method="get" action="">
                        <div class="card-header">
                            <div class="card-tools">
                                <div class="input-group input-group" style="width: 250px;">
                                    <input value="{{Request::get('keyword')}}" type="number" name="keyword" class="form-control float-right" placeholder="Search">
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-default">
                                            <i class="fas fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                    @include('admin.messages')
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover text-nowrap">
                            <thead>
                                <tr>
                                    <th width="60">ID</th>
                                    <th>Code</th>
                                    <th>Discount</th>
                                    <th>Expire</th>
                                    <th width="100">Status</th>
                                    <th width="100">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            @if($coupons->isNotEmpty())
                                @foreach($coupons as $coupon)
                                    <tr>
                                        <td>{{$coupon->id}}</td>
                                        <td>{{$coupon->code}}</td>
                                        <td>{{$coupon->discount}}</td>
                                        <td>{{$coupon->expire}}</td>
                                        <td>
                                        @if($coupon->expire > Carbon\Carbon::today() &&
                                            $coupon->status == 1
                                        )
                                                <svg class="text-success-500 h-6 w-6 text-success" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
                                                    <path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                                                </svg>
                                        @else
                                                <svg class="text-danger h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
                                                    <path stroke-linecap="round" stroke-linejoin="round" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                                                </svg>
                                        @endif
                                        </td>
                                        <td>
                                            <a href="{{route('coupons.edit',$coupon->id)}}">
                                                <svg class="filament-link-icon w-4 h-4 mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                                    <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"></path>
                                                </svg>
                                            </a>
                                        <form id="delete-form" action="{{ route('coupons.destroy', $coupon->id) }}" method="post">
                                            @method('DELETE')
                                            @csrf
                                            <a onclick="event.preventDefault(); document.getElementById('delete-form').submit();" class="text-danger w-4 h-4 mr-1">                                                <svg wire:loading.remove.delay="" wire:target="" class="filament-link-icon w-4 h-4 mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                                    <path	ath fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"></path>
                                                </svg>
                                            </a>
                                        </form>
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                            <tr>
                                <td colspan="5">
                                    Records Not Found
                                </td>
                            </tr>
                            @endif

                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer clearfix">
                        <ul class="pagination pagination m-0 float-right">
                          {{$coupons->links()}}
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /.card -->
        </section>
        <!-- /.content -->
@endsection